import { Receipt } from '@/types';
import { getTransactionExplorerUrl } from './transactions';

export async function generateReceiptPDF(receipt: Receipt): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const purple = [124, 58, 237] as [number, number, number];
  const teal = [13, 148, 136] as [number, number, number];
  const dark = [30, 30, 30] as [number, number, number];
  const gray = [120, 120, 120] as [number, number, number];

  doc.setFillColor(...purple);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('SOLVIO', 14, 14);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Solana Payment Hub', 14, 21);

  const receiptLabel = receipt.type === 'split' ? 'Split Receipt' : 'Payment Receipt';
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...dark);
  doc.text(receiptLabel, 14, 40);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...gray);
  doc.text(`Receipt ID: ${receipt.id}`, 14, 47);
  doc.text(`Date: ${new Date(receipt.date).toLocaleString()}`, 14, 53);

  doc.setDrawColor(...teal);
  doc.setLineWidth(0.5);
  doc.line(14, 57, 196, 57);

  let y = 65;
  doc.setFontSize(10);
  doc.setTextColor(...dark);

  const addRow = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...gray);
    doc.text(label, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...dark);
    doc.text(value, 80, y);
    y += 7;
  };

  addRow('Amount:', `${receipt.amount} ${receipt.currency}`);
  addRow('From:', receipt.fromAddress.slice(0, 20) + '...' + receipt.fromAddress.slice(-6));
  addRow('To:', receipt.toAddress.slice(0, 20) + '...' + receipt.toAddress.slice(-6));

  if (receipt.note) {
    addRow('Note:', receipt.note);
  }

  if (receipt.txId) {
    y += 3;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...gray);
    doc.text('Transaction ID:', 14, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...teal);
    const link = getTransactionExplorerUrl(receipt.txId);
    doc.textWithLink(receipt.txId.slice(0, 30) + '...', 80, y, { url: link });
    y += 7;
  }

  if (receipt.participants && receipt.participants.length > 0) {
    y += 5;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...dark);
    doc.text('Participants:', 14, y);
    y += 7;

    receipt.participants.forEach((p) => {
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...dark);
      const statusColor = p.status === 'confirmed' ? [16, 185, 129] : p.status === 'failed' ? [239, 68, 68] : [245, 158, 11];
      doc.setFillColor(...(statusColor as [number, number, number]));
      doc.roundedRect(14, y - 4, 170, 6, 1, 1, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text(`${p.nickname} | ${p.address.slice(0, 12)}... | ${p.amount} ${receipt.currency} | ${p.status.toUpperCase()}`, 16, y);
      y += 8;
    });
  }

  y += 5;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...gray);
  doc.text('Generated by Solvio — Solana Payment Hub', 14, y);

  const filename = `solvio-receipt-${receipt.id.slice(0, 8)}.pdf`;
  doc.save(filename);
}
